<a href="https://colab.research.google.com/github/14anu/ML/blob/main/introduction/numpy_5th_sem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Introduction to NumPy

what we will cover?

*   Creating arrays
*   Multidimensional array
*   Randomly generated arrays
*   Element wise operations
*   Summarizing operations





# Single dimensional arrays

In [2]:
import numpy as np
# create an array with all the elements to be zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
#creating an array with all elements 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
# create an array of size 10 with all elements 3
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [5]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [7]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [10]:
# create an array with evenly spaced numbers within a specified range
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multidimensional arrays

In [11]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a[0,1]=20
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [18]:
a[2]=[1, 1, 1]
a

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [19]:
a[:, 2] = [2, 2, 2]
a

array([[ 1, 20,  2],
       [ 4,  5,  2],
       [ 1,  1,  2]])

In [21]:
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# Randomly generated arrays



*   NumPy can create arrays filled with random numbers
*   To ensure the reductibility, you can set a seed using np.random.    (). It will generate the exact same random numbers for each executions.
*   If you remove or change the seed values, the sequence of random numbers will be changed.




In [22]:
np.random.rand(5)

array([0.46305502, 0.62073854, 0.81834797, 0.23243034, 0.61194415])

In [23]:
np. random.seed(80)
np.random.rand(5)

array([0.52191572, 0.69940637, 0.26986897, 0.67448187, 0.90807208])

In [24]:
np.random.randn(5, 2)

array([[-1.03446493,  0.66424004],
       [-1.13937438, -0.89472205],
       [-0.2207972 , -0.43007258],
       [ 1.19972246,  0.1222967 ],
       [ 0.54794733, -0.52658091]])

In [25]:
np.random.randint(low=0, high=100, size=(5, 2))

array([[ 7, 69],
       [96, 56],
       [15,  3],
       [94, 39],
       [51, 94]])